openapi: "3.0.0"
info:
  title: "Coin Surfer Server"
  description: "coin_surfer server component for API interfaces."
  version: "1.0.0"
servers:
  - url: /api

paths:
  /health:
    get:
      tags: ["Health"]
      operationId: "server.controllers.health.get_health"
      summary: "Health check."
      responses:
        '200':
          description: "OK"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /trading/{tradingId}/backtest:
    get:
      tags: ["Backtesting"]
      operationId: "api.controllers.backtest.execute"
      summary: "Execute a specific backtest."
      parameters:
        - name: tradingId
          in: path
          required: true
          schema:
            type: string
      responses:
          '200':
            $ref: "#/components/responses/HttpTradingBacktestResponse"
          '400':
            $ref: '#/components/responses/HttpBadRequest'
          '500':
            $ref: '#/components/responses/HttInternalServerError'
  /portfolio/{wallet_type}/{portfolioId}:
    get:
      tags: ["Portfolio"]
      operationId: "api.controllers.portfolio.get_portfolio"
      summary: "Return details for a named portfolio."
      parameters:
        - name: wallet_type
          in: path
          required: true
          schema:
            type: string
            enum:
              - coinbase
              - metamask
        - name: portfolioId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          $ref: '#/components/responses/HttpPortfolioBreakdownGetResponseSuccess'
        '400':
          $ref: '#/components/responses/HttpBadRequest'
        '500':
          $ref: "#/components/responses/HttInternalServerError"

components:
  responses:
    HttpBadRequest:
      description: 400 - Bad Request.
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                description: A message for troubleshooting purposes.
    HttInternalServerError:
      description: 500 - Internal Server Error
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                description: A message for troubleshooting purposes.
    HttpPortfolioBreakdownGetResponseSuccess:
      description: '200 - Document will follow.'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PortfolioBreakdown'

  schemas:
    PortfolioBreakdown:
      type: object
      properties:
        data:
          type: string
